export const PERGUNTAS_PT_ALTURA: readonly string[] = [
  "O trabalho é acima de 2 metros?",
  "Oferece risco de queda ao colaborador?",
  "O treinamento em altura dos colaboradores está em dia?",
  "Há procedimento para execução do trabalho?",
  "Foi feito isolamento da área?",
  "Os pontos de ancoragem são seguros?",
  "Capacete",
  "Óculos",
  "Cinturão paraquedista",
  "Corda/cabo de aço",
  "Trava-quedas adequado",
  "Talabarte adequado",
  "Luvas",
  "Outros",
  "Os equipamentos estão adequados para o uso?",
  "Há risco adicional como elétrico?",
  "Foram tomadas medidas preventivas a quedas de objetos e ferramentas?",
  "(Em caso de área externa) As condições climáticas são adequadas?",
  "As escadas estão em condições adequadas de uso?",
  "O apoio para escada é adequado?",
  "A escada contém antiderrapante?",
  "A escada extensiva possui trava segura?",
  "O andaime foi montado por uma equipe qualificada?",
  "O andaime está nivelado?",
  "A base é no mínimo 1/4 da altura do andaime?",
  "A ancoragem é independente da estrutura do andaime?",
  "As tábuas do andaime estão fixas e em perfeitas condições de uso?",
  "O andaime tem guarda-corpo?",
  "Há uma equipe e equipamentos em condições para resgate, em casos de emergências?",
] as const;
